"""add nodes

Revision ID: 4a819e87e473
Revises: f5984f68b4b5
Create Date: 2026-06-12 08:52:06.411927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a819e87e473'
down_revision: Union[str, Sequence[str], None] = 'f5984f68b4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'nodes',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('host', sa.String(length=255), nullable=False),
        sa.Column('port', sa.Integer(), nullable=False),
        sa.Column('role', sa.Enum('MEDIA_SERVER', 'LOAD_SERVER', name='noderole'), nullable=False),
        sa.Column('status', sa.Enum('UNKNOWN', 'ONLINE', 'OFFLINE', name='nodestatus'), nullable=False, server_default=sa.text("'UNKNOWN'")),
        sa.Column('last_seen', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('ssh_login', sa.String(length=128), nullable=True),
        sa.Column('ssh_password', sa.String(length=128), nullable=True),
        sa.Column('enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodes')
    # ### end Alembic commands ###
