"""add run timestamps

Revision ID: f5984f68b4b5
Revises: 58d4017bf222
Create Date: 2026-06-11 18:46:44.883841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5984f68b4b5'
down_revision: Union[str, Sequence[str], None] = '58d4017bf222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_runs', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('test_runs', sa.Column('finished_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_runs', 'finished_at')
    op.drop_column('test_runs', 'started_at')
    # ### end Alembic commands ###
